import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" flex flex-col h-screen" suppressHydrationWarning={true}>
        <header className="grid grid-cols-8 text-center gap-x-0.5 ">
          <div className="bg-slate-200 p-2">File</div>
          <div className="col-start-2 col-end-6 bg-slate-200 p-2">Box</div>
          <div className="bg-slate-200 p-2">Connection</div>
          <div className="col-start-7 col-end-9 bg-slate-200  p-2">Report</div>
        </header>
        <Nav />
        <div className="h-full">{children}</div>
      </body>
    </html>
  );
}
